Add Moodle support to the LTI Launch Library
oxctl/lti-launch pull request #25
Opened 2022-02-28 12:11 UTC by mpellicer

I spent some time on the library to make it work with Moodle since I'm creating a LTI 1.1 tool that is running fine in Canvas and Moodle, I just want a light opinion about this work since I don't neccessary need all the changes, if this work is not interesting for the LTI Launch library I'm fine!

Thanks!

2022-03-03 09:39 UTC, buckett requested changes
Yeah, would be good to add support for Moodle to the library.

2022-03-03 09:39 UTC, buckett commented on lti-launch-core/pom.xml
> +        </dependency>
For libraries I think it's nice to not use lombok as the source matches the built files.

2022-03-03 10:13 UTC, mpellicer commented on lti-launch-core/pom.xml
> +        </dependency>
I made a fork of the library and added Moodle support, I've implemented an LTI tool with the changes and works fine in both Canvas and Moodle, don't need the changes necessary because I always have the LaunchData object but it's easier to call getMoodleCourseId or getCanvasCourseId, they use different attributes of the payload. We're also going to use the library in Brightspace so this work could be contributed too.

Agreed about the lombok dependency, I'll remove it!

Thanks for your time Matthew and have a nice week!

2022-04-08 09:29 UTC, buckett approved these changes

2022-04-08 09:29 UTC, buckett approved these changes
Thanks.

2022-04-08 09:29 UTC, merged

2022-04-08 09:30 UTC, buckett commented
Thanks @mpellicer. Are you wanting a published release for this change?

2022-04-08 09:34 UTC, mpellicer commented
Thanks @buckett, I don't need a release for this and we expect to add support to D2L too in the future, it's fine as is.